name: gradle and docker

on:
 push:
   branches:
     - main

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
     
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      - name: Build docker image and push to hub
        run: |
            rm -rf src/test
            gradle build
            docker build -t test-api:0.1 .
            images_id=$(docker images -qa test-api:0.1)
            docker tag $images_id wjdqlsdlsp/test-api:0.1
            docker push wjdqlsdlsp/road-helper:0.1
